### ISSUE TITLE
markdown 头部格式的问题

### ISSUE THREAD

**Issue by HenryQW** [VincentBel/remark-pangu#14]
```js

        remark()
            .use(pangu)
            .process(newContent, (err, result) => {
                if (err) {
                    return Promise.reject(err);
                }
                newContent = String(result);
            });
```

会把头部的 (frontmatter?)

```
---
pageClass: routes
---
```

弄得很奇怪

![image](https://user-images.githubusercontent.com/5896343/80895411-7d3c0280-8cdc-11ea-9592-5d633b7966d9.png)

![image](https://user-images.githubusercontent.com/5896343/80895463-1cf99080-8cdd-11ea-8d91-82b29c7d7d42.png)

请问有没有解决办法？

https://github.com/DIYgod/RSSHub/pull/4654#issuecomment-623033419

**Comment by VincentBel** [comment]
@HenryQW 

```
---
pageClass: routes
---
```

这个是 frontmatter，你需要添加 frontmatter plugin 才能处理：https://github.com/remarkjs/remark-frontmatter

**Comment by HenryQW** [comment]
十分感谢！
